"""added the pic_file_path to the db

Revision ID: f3576ca73f6c
Revises: dbfc099c25ad
Create Date: 2023-01-08 18:33:16.403391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3576ca73f6c'
down_revision = 'dbfc099c25ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('subtitle')
        batch_op.drop_column('title')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_file_path', sa.String(length=100), nullable=True))
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DATETIME(), nullable=True))
        batch_op.drop_column('pic_file_path')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('subtitle', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
